### ISSUE TITLE
skip over null bytes

### ISSUE THREAD

**Issue by muelli** [linuxCowboy/vbl#1]
When looking at my disk image, I see many null bytes that I don't care about. I would like to skip over them. Forward and backward.

**Comment by linuxCowboy** [comment]
For this common case I implemented "Next/Prev different Byte" with `PgDn` and `PgUp`.

In single mode you can use a feature called *Smartscroll* to collapse any identical lines while scrolling forward.

**Comment by muelli** [comment]
yeah, I noticed that there is no simple "scroll further by one page" function. Especially not in the "smart scroll' mode. It takes quite some time for my 2TB file to enter the smart scoll mode and trying to navigate "one page up" results in a loss of precious state.

**Comment by linuxCowboy** [comment]
Of course is there a _scroll-down_ function. And yes, _Smartscroll_ works only in forward direction.

**Comment by muelli** [comment]
how would I navigate "one page up" in two-file mode? When I press arrow-up, it scrolls by one line. If I press Page-up, then it goes to the next different byte (although it remains unclear to me which byte is taken as reference). Space bar seems to scroll one page down, but shift-space does not scroll back up.

**Comment by linuxCowboy** [comment]
_Backspace_ and the _top left_ Byte.
