### ISSUE TITLE
go to relative offset (i.e. +6000)

### ISSUE THREAD

**Issue by muelli** [linuxCowboy/vbl#2]
I want to advance the current view by a certain number of bytes, say 6000. I would like to be able to press "g" and then "+6000".

**Comment by linuxCowboy** [comment]
Good idea. I will add _relative jumps_ **+/-** to my to-do list.

**Comment by linuxCowboy** [comment]
done: [v2.13](https://github.com/linuxCowboy/vbl/releases/tag/v2.13)

**Comment by muelli** [comment]
works very well. Thanks!
I wonder: can I scroll the same amount with a single key?

**Comment by linuxCowboy** [comment]
with 3 keys: `g`, `up`, `Enter`

**Comment by linuxCowboy** [comment]
with 1 key: [v2.15](https://github.com/linuxCowboy/vbl/releases/tag/v2.15)
