### ISSUE TITLE
control to number of bytes displayed per line

### ISSUE THREAD

**Issue by muelli** [linuxCowboy/vbl#3]
Currently, when I full screen the window, it draws three vertical separation lines, indicating that it renders 24 bytes per line.

![image](https://github.com/linuxCowboy/vbl/assets/322807/64c3ecea-74db-4c21-816b-a039a25ff03d)

However, I want to make it render "normal" 16 bytes per line.

**Comment by linuxCowboy** [comment]
Enlarge your screen font or shrink your terminal under 108 columns.

**Comment by muelli** [comment]
yeah, thanks for the pointer. But somehow the app does not like the width of the terminal changing.  And I also dislike the idea of having to resize my terminal. I don't think I want to ever look at more than the classic two columns. So if I could start the app with a flag or something, I would be happy.

**Comment by linuxCowboy** [comment]
Change the width _before_ you lunch **vbl**!

**Comment by muelli** [comment]
yeah, that's much more annoying than starting vbl with `--max-columns=2` or something.

**Comment by linuxCowboy** [comment]
Apply this patch for static 16 Byte: [static-16byte.patch.txt](https://github.com/linuxCowboy/vbl/files/11918246/static-16byte.patch.txt)

**Comment by muelli** [comment]
excellent. Works very well for me. Thanks!
