### ISSUE TITLE
find (text) backwards

### ISSUE THREAD

**Issue by muelli** [linuxCowboy/vbl#4]
I am currently scrolling through a disk image. I am going from the bottom up and I'm seeing artefacts of a PDF document. Now I want to search for, say, "stream", to skip over binary data. But the search needs to go towards the top of the file, not the bottom.

**Comment by linuxCowboy** [comment]
You have to load the search buffer to activate the `N` and `P` menu points.

But you can nevertheless press `p` instead of `f` to search directly backwards.

**Comment by muelli** [comment]
excellent. Thanks and sorry for the noise!
