### ISSUE TITLE
Option to toggle DIfference visual

### ISSUE THREAD

**Issue by Osmous** [linuxCowboy/vbl#5]
Maybe add a keybind to keep difference from disappearing after pressing arrow keys. currently after finding difference using the enter key and scrolling using arrow keys, the difference colors disappears. altho i do not know how difficult it would be to implement such a feature. Thanks :D

**Comment by linuxCowboy** [comment]
Hello Osmous,

here is a quick patch for you:

[arrows.txt](https://github.com/user-attachments/files/16691115/arrows.txt)

apply it with:

`patch --verbose vbl.cpp arrows.txt
`

**Comment by Osmous** [comment]
Thanks works like a charm!
